include: package:very_good_analysis/analysis_options.2.4.0.yaml

analyzer:
  exclude:
    - lib/generated/*
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.mocks.dart"
linter:
  rules:
    directives_ordering: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    prefer_if_elements_to_conditional_expressions: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false