coverage:
  range: "95...100"
  status:
    project:
      default:
        target: 100
ignore:
  - '**/*freezed.dart'
  - '**/*g.dart'
  - '**/*gr.dart'
  - '**/*dto.dart'
  - '**/providers.dart'
  - 'lib/core/presentation/bootstrap.dart'
  - 'lib/core/infrastructure/remote_response.dart'
  - 'lib/core/infrastructure/network_exceptions.dart'
  - 'lib/core/infrastructure/sembast_database.dart'
