// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOiTMV-sXcf4imzPXBBD4A5po-I9OSyZI',
    appId: '1:1053138325070:web:a4600ead344d9874443d1f',
    messagingSenderId: '1053138325070',
    projectId: 'flutter-template-b8338',
    authDomain: 'flutter-template-b8338.firebaseapp.com',
    storageBucket: 'flutter-template-b8338.appspot.com',
    measurementId: 'G-2K7C5LBJ8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcUlIpeOnyz8scs1QN8-JXuzfzUzVjc1E',
    appId: '1:1053138325070:android:fbf3ae8fd399932c443d1f',
    messagingSenderId: '1053138325070',
    projectId: 'flutter-template-b8338',
    storageBucket: 'flutter-template-b8338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqV91bedYH8ajiiI1l-Xpp39uUGfzfUnk',
    appId: '1:1053138325070:ios:9f509e54e5a6f191443d1f',
    messagingSenderId: '1053138325070',
    projectId: 'flutter-template-b8338',
    storageBucket: 'flutter-template-b8338.appspot.com',
    iosClientId: '1053138325070-5na3tr9la37l20a90093a9c9cdl3gu6h.apps.googleusercontent.com',
    iosBundleId: 'com.jparrack.flutter-template',
  );
}
